Add sorting through proposals
godot-proposals-viewer/godot-proposals-viewer.github.io pull request #4
Opened 2021-04-13 05:16 UTC by foxydevloper

Adds sorting options for Score, Newest, Oldest

https://user-images.githubusercontent.com/12120644/114500231-9ee48000-9bf5-11eb-98bc-89f27f08bbe2.mp4

2021-04-13 06:24 UTC, foxydevloper commented
whoops  i tried squashing the commits and managed to fail miserably

2021-04-13 11:13 UTC, Calinou requested changes

2021-04-13 11:13 UTC, Calinou commented on index.html
> +            var sortMethod
```suggestion
            let sortMethod;
```

2021-04-13 11:13 UTC, Calinou commented on index.html
> +          },
```suggestion
          sortProposalsOldest(a, b) {
            if (a.number > b.number) {
              return 1;
            }
            
            return -1;
          },
```

2021-04-13 11:13 UTC, Calinou commented on index.html
> +          },
```suggestion
          sortProposalsNewest(a, b) {
            if (a.number < b.number) {
              return 1;
            }
            
            return -1;
          },
```

2021-04-13 23:51 UTC, foxydevloper reviewed
epic

2021-04-15 14:27 UTC, Calinou approved these changes
Thanks! Congratulations for your first merged pull request :tada:

2021-04-15 14:27 UTC, merged